Introduce personal to roles

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -17,4 +17,17 @@ fi
 if [ ! -e bin/$MITAMAE_BIN ] || [ $MITAMAE_VERSION != $CURRENT_MITAMAE_VERSION ]; then
   (cd bin; curl -sSL https://github.com/itamae-kitchen/mitamae/releases/download/v${MITAMAE_VERSION}/${MITAMAE_BIN}.tar.gz | tar xvz)
 fi
-bin/$MITAMAE_BIN local roles/work.rb
+
+while getopts ":r:" opt; do
+  case $opt in
+    r)
+      if [[ ! "$OPTARG" =~ ^(work|personal)$ ]]; then
+        echo "error: invalid role '$OPTARG'" >&2
+        exit 1
+      fi
+      ROLE=$OPTARG
+      ;;
+  esac
+done
+
+bin/$MITAMAE_BIN local roles/${ROLE:-work}.rb
